export interface Article {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  body: string;
  category: string;
  author: string;
  authorAvatar: string;
  date: string;
  readTime: string;
  image: string;
  featured: boolean;
}

export const categories = [
  "All",
  "Design",
  "Technology",
  "Culture",
  "Travel",
  "Fashion",
  "Architecture",
];

export const articles: Article[] = [
  {
    id: 1,
    slug: "future-of-digital-design",
    title: "The Future of Digital Design Is Already Here",
    excerpt:
      "From AI-generated layouts to spatial computing interfaces, the digital design landscape is evolving at an unprecedented pace.",
    body: `The boundaries between physical and digital design continue to blur at an accelerating pace. What was once considered science fiction — interfaces that adapt to your emotions, layouts generated by artificial intelligence, and experiences that span the gap between screens and physical spaces — is now becoming our everyday reality.

In studios across the world, designers are grappling with a fundamental shift in their craft. The tools are changing, the mediums are expanding, and the expectations of users have never been higher. Yet amid this transformation, the core principles of good design remain remarkably constant: clarity, empathy, and purpose.

The rise of generative AI has introduced a new dynamic to the creative process. Rather than replacing designers, these tools are amplifying their capabilities, allowing them to explore vast solution spaces in minutes rather than weeks. The best designers are learning to work with AI as a collaborative partner, feeding it constraints and refining its output with the nuanced judgment that only human experience can provide.

Spatial computing represents another frontier. As headsets become lighter and more capable, designers must think in three dimensions, considering not just how elements look on a flat screen, but how they exist in space around the user. This demands new mental models and new vocabularies for interaction.

Perhaps most importantly, the democratization of design tools means that good design is no longer the exclusive domain of specialists. When everyone can create, the role of the professional designer shifts from executor to educator, curator, and systems thinker.

The future of digital design isn't a destination — it's a direction. And those who embrace the journey with curiosity and conviction will be the ones who shape what comes next.`,
    category: "Design",
    author: "Elena Marchetti",
    authorAvatar: "https://i.pravatar.cc/100?img=1",
    date: "March 15, 2026",
    readTime: "8 min read",
    image: "https://picsum.photos/seed/design-future/1200/800",
    featured: true,
  },
  {
    id: 2,
    slug: "quiet-revolution-sustainable-architecture",
    title: "The Quiet Revolution in Sustainable Architecture",
    excerpt:
      "How a new generation of architects is reimagining buildings as living systems that heal rather than harm.",
    body: `Across the skylines of major cities, a quiet revolution is taking place. A new generation of architects is moving beyond the green certifications and solar panels of the past decade toward something far more ambitious: buildings that function as living ecosystems.

These structures don't just minimize harm — they actively regenerate. Living walls filter air pollution while producing oxygen. Integrated mycelium networks process waste into usable compost. Rainwater harvesting systems not only serve the building but replenish local aquifers.

The shift reflects a deeper philosophical change in architecture. Rather than imposing human will on the environment, these designers are learning from nature's patterns — biomimicry at the grandest scale. The result is architecture that breathes, adapts, and evolves with its surroundings.

Materials science is playing a crucial role. Self-healing concrete embedded with bacteria that produce limestone when cracked. Transparent wood that insulates better than glass. Algae-infused panels that generate energy from photosynthesis. These innovations are turning buildings from static objects into dynamic organisms.

The economic case is becoming undeniable. While sustainable buildings cost 5-10% more upfront, they save 30-50% in operating costs over their lifetime. Insurance companies are beginning to offer lower premiums for regenerative buildings, recognizing their resilience against climate events.

This is architecture not as monument, but as medicine — healing the landscapes we've spent centuries degrading.`,
    category: "Architecture",
    author: "James Okonkwo",
    authorAvatar: "https://i.pravatar.cc/100?img=3",
    date: "March 12, 2026",
    readTime: "6 min read",
    image: "https://picsum.photos/seed/architecture-green/1200/800",
    featured: false,
  },
  {
    id: 3,
    slug: "art-of-slow-travel",
    title: "The Art of Slow Travel in a Hyperconnected World",
    excerpt:
      "Why the most meaningful journeys are the ones where you put away your phone and let the world unfold.",
    body: `In an age where we can fly anywhere in hours and share every moment instantly, a growing movement is choosing to do the opposite. Slow travel — the art of lingering, of going deeper rather than farther — is having its moment.

The concept isn't new. Grand tourists of the 18th century spent months in a single city. But today's slow travelers are motivated by something different: a desire to escape the curated, Instagram-ready version of travel and rediscover the serendipity of genuine exploration.

The practice takes many forms. Some travel by train across continents, watching landscapes shift gradually through the window. Others settle in small towns for weeks, shopping at local markets and learning to cook regional dishes. A few have sworn off air travel entirely, finding that the constraint forces creativity.

What unites them is a rejection of the checklist mentality — the compulsion to see every landmark, eat at every recommended restaurant, and document it all. Instead, they measure the value of travel in conversations with strangers, in afternoons spent lost in unfamiliar neighborhoods, in the quiet moments between destinations.

The science supports this approach. Research shows that anticipation and reflection — the mental bookends of travel — contribute more to happiness than the trip itself. Slow travel naturally extends both, allowing experiences to settle into memory rather than blur together.

In a hyperconnected world, the most radical act might be disconnecting long enough to actually see where you are.`,
    category: "Travel",
    author: "Sofia Lindgren",
    authorAvatar: "https://i.pravatar.cc/100?img=5",
    date: "March 10, 2026",
    readTime: "5 min read",
    image: "https://picsum.photos/seed/slow-travel/1200/800",
    featured: false,
  },
  {
    id: 4,
    slug: "neural-interfaces-creative-expression",
    title: "Neural Interfaces and the Next Wave of Creative Expression",
    excerpt:
      "Brain-computer interfaces are opening doors to art forms we haven't imagined yet.",
    body: `The first time Maya Chen connected her neural interface to a digital canvas, she cried. Not from the technology itself, but from the realization of how much creative intention gets lost between thought and execution.

With the interface, the gap vanished. Colors appeared as she felt them. Shapes flowed with the rhythm of her emotions. The artwork was raw, unmediated, and startlingly honest.

Neural interfaces for creative expression are still in their infancy, but early experiments suggest they could fundamentally alter our relationship with art. Musicians are composing by thinking in melodies. Sculptors are shaping virtual clay with spatial thoughts. Writers are exploring narratives that branch along emotional pathways.

The technology raises profound questions about authorship and authenticity. If art is the product of thought rather than craft, what role does skill play? If a neural interface can translate anyone's inner world into visual form, does the distinction between artist and non-artist dissolve?

These questions parallel earlier debates about photography (does the machine create the art?) and digital tools (is it still painting if you use Photoshop?). History suggests we'll integrate neural interfaces into our creative vocabulary just as we have every previous tool.

But something genuinely new is happening here. For the first time, the medium is consciousness itself. And what that means for human expression is a story still being written — or rather, being thought into existence.`,
    category: "Technology",
    author: "Raj Patel",
    authorAvatar: "https://i.pravatar.cc/100?img=8",
    date: "March 8, 2026",
    readTime: "7 min read",
    image: "https://picsum.photos/seed/neural-art/1200/800",
    featured: false,
  },
  {
    id: 5,
    slug: "renaissance-of-handmade-fashion",
    title: "The Renaissance of Handmade Fashion",
    excerpt:
      "In a world of fast fashion, artisans are reclaiming the craft of making clothes by hand.",
    body: `Walk into Maison Lumière in Paris's 11th arrondissement, and you'll find something increasingly rare: a workshop where every garment is made entirely by hand. The hum of sewing machines is absent. Instead, you hear the soft pull of needle through fabric, the snip of scissors, the quiet conversation of artisans at work.

Founded by former luxury house designer Camille Beaumont, Maison Lumière is part of a growing movement to reclaim fashion as craft. In an industry that produces 100 billion garments annually — most destined for landfills within a year — the return to handmade represents both a aesthetic choice and a moral stance.

The economics are challenging. A hand-sewn jacket takes 80 hours to complete, compared to 30 minutes on an industrial line. The resulting price reflects this: Maison Lumière pieces start at €2,000. But Beaumont argues the comparison is misleading.

"You're not buying a jacket," she says. "You're buying the knowledge of hands that have been perfecting this craft for decades. You're buying a garment that will last your lifetime and can be repaired, not replaced."

The movement is finding unexpected allies in technology. 3D body scanning creates precise measurements without wasteful samples. Digital pattern-making reduces fabric waste to near zero. Social media connects artisans directly with customers who value their story.

A new generation of consumers is driving the shift. They're buying fewer, better things. They want to know who made their clothes and how. They see fashion not as disposable trend-following but as personal expression with lasting value.

The handmade renaissance isn't anti-modern. It's the most modern response possible to the excesses of industrial fashion.`,
    category: "Fashion",
    author: "Amara Johnson",
    authorAvatar: "https://i.pravatar.cc/100?img=9",
    date: "March 5, 2026",
    readTime: "6 min read",
    image: "https://picsum.photos/seed/handmade-fashion/1200/800",
    featured: false,
  },
  {
    id: 6,
    slug: "typography-as-rebellion",
    title: "Typography as Rebellion: How Fonts Shape Movements",
    excerpt:
      "From punk zines to protest posters, typography has always been a tool of cultural resistance.",
    body: `Every revolution has its typeface. The blocky Futura of Bauhaus. The jagged letterforms of punk. The clean Helvetica of corporate counter-culture. Typography is never neutral — it carries the weight of ideology in every curve and serif.

Today, a new generation of type designers is wielding this power with intention. Variable fonts that shift weight based on the reader's emotional state. Typefaces designed specifically for dyslexic readers. Scripts that preserve endangered languages in digital form.

The history of typography as rebellion is rich and often surprising. In the 1960s, Letraset transfer lettering democratized type design, enabling anyone with a burnishing tool to set professional-looking headlines. Punk zines of the 1970s deliberately rejected this professionalism, using hand-scrawled type as a rejection of polished media.

The desktop publishing revolution of the 1980s triggered another wave. Suddenly, anyone with a Macintosh could create a newsletter, a poster, a manifesto. The establishment decried the resulting "ugliness" — but that ugliness was the point. It was communication freed from gatekeepers.

Today's typographic rebellion is more subtle but no less significant. Open-source font movements are challenging the monopoly of major foundries. AI-assisted type design is making custom typefaces accessible to independent publishers. And a growing awareness of typographic colonialism — the dominance of Latin scripts in global design — is driving the creation of beautiful, functional typefaces for underrepresented writing systems.

The next time you choose a font, remember: you're not just selecting a style. You're casting a vote for a worldview.`,
    category: "Culture",
    author: "Marcus Rivera",
    authorAvatar: "https://i.pravatar.cc/100?img=12",
    date: "March 2, 2026",
    readTime: "5 min read",
    image: "https://picsum.photos/seed/typography-rebel/1200/800",
    featured: false,
  },
  {
    id: 7,
    slug: "ambient-computing-invisible-interfaces",
    title: "Ambient Computing: When Interfaces Disappear",
    excerpt:
      "The best technology is the kind you forget is there. Welcome to the age of invisible interfaces.",
    body: `The most successful technology of the next decade won't be something you see, hold, or interact with consciously. It will be ambient — woven so seamlessly into your environment that you forget it exists.

This is the promise of ambient computing, and it's closer than you think. Smart surfaces that adjust room temperature based on occupancy. Lighting that shifts spectrum throughout the day to support your circadian rhythm. Audio environments that adapt to whether you're working, socializing, or sleeping.

The philosophical shift is profound. For decades, we've designed technology that demands attention — notifications, badges, pop-ups all competing for our finite cognitive resources. Ambient computing inverts this relationship. Instead of you adapting to technology, technology adapts to you.

The challenges are significant. Privacy concerns multiply when sensors are everywhere. The energy cost of always-on computing must be addressed. And there's a genuine question about agency: if your environment is constantly optimizing around you, who's making the decisions?

Leading thinkers in the field argue for what they call "legible ambience" — environments that are responsive but transparent. A light that dims shouldn't just dim; there should be a way to understand why and override it. The environment should feel like a helpful colleague, not an unseen puppeteer.

The irony is that achieving invisible technology requires extraordinary design effort. Making something feel effortless demands meticulous attention to every edge case, every transition, every moment where the system's model of you might diverge from reality.

The future isn't about better screens. It's about no screens at all.`,
    category: "Technology",
    author: "Elena Marchetti",
    authorAvatar: "https://i.pravatar.cc/100?img=1",
    date: "February 28, 2026",
    readTime: "7 min read",
    image: "https://picsum.photos/seed/ambient-tech/1200/800",
    featured: false,
  },
  {
    id: 8,
    slug: "forgotten-gardens-of-kyoto",
    title: "The Forgotten Gardens of Kyoto",
    excerpt:
      "Beyond the tourist trails, Kyoto hides gardens that have been tended for centuries by a single family.",
    body: `Down a narrow alley in Kyoto's Higashiyama district, behind an unmarked wooden gate, lies a garden that has been tended by the Nakamura family for seventeen generations. There is no website, no TripAdvisor listing, no Instagram account. The garden exists, as it has for four hundred years, for those who know to look for it.

Kenji Nakamura, the current keeper, rises at 4 AM each morning to rake the gravel and tend the moss. The patterns he creates are not decorative — they're a form of meditation, each stroke of the rake a breath, each curve a thought released. By the time the first light hits the garden, it's a fresh canvas.

Kyoto has over two thousand temples and shrines, many with famous gardens that draw millions of visitors annually. But scattered throughout the city are dozens of private gardens like the Nakamuras', maintained not for tourists but for the families and communities they serve.

These gardens embody the Japanese concept of wabi-sabi — the beauty of imperfection and impermanence. A stone placed slightly off-center. Moss allowed to claim a stepping stone. The way autumn leaves are left to decompose naturally rather than cleared away.

For Nakamura, the garden is a conversation across time. "I am speaking with my grandfather's grandfather," he says, adjusting a stone that has sat in the same spot since the Edo period. "He placed this. I maintain the dialogue."

In a world obsessed with the new, Kyoto's forgotten gardens offer a radical alternative: the beauty of something old, cared for, and allowed to change at its own pace.`,
    category: "Travel",
    author: "Sofia Lindgren",
    authorAvatar: "https://i.pravatar.cc/100?img=5",
    date: "February 25, 2026",
    readTime: "6 min read",
    image: "https://picsum.photos/seed/kyoto-garden/1200/800",
    featured: false,
  },
  {
    id: 9,
    slug: "color-theory-digital-age",
    title: "Color Theory in the Digital Age: Beyond the Wheel",
    excerpt:
      "How screens, dark modes, and accessibility requirements are rewriting the rules of color.",
    body: `The color wheel that every design student learns is a lie — or at least, a vast oversimplification. In the digital age, where colors are rendered by millions of individual light-emitting pixels across devices with wildly different calibrations, the neat theories of complementary and analogous colors barely scratch the surface.

Consider dark mode. When Apple and Google introduced system-wide dark modes, they inadvertently launched the largest color theory experiment in history. Designers discovered that simply inverting colors produced muddy, unreadable interfaces. True dark mode requires rethinking the entire color relationship — reducing saturation, adjusting contrast ratios, and understanding how the eye perceives color differently on dark backgrounds.

Accessibility has added another layer of complexity. WCAG guidelines require minimum contrast ratios between text and background, which constrains palette choices in ways that traditional color theory never anticipated. The challenge isn't just making things beautiful — it's making them beautiful within strict functional parameters.

P3 wide-gamut displays are expanding the visible color space beyond what sRGB offered for decades. Colors that were literally impossible to display are now available, and designers are only beginning to explore this expanded palette.

Meanwhile, research into color psychology is becoming more nuanced. The old rules ("blue is calming, red is exciting") are giving way to understanding how cultural context, personal experience, and even time of day affect color perception. A color palette that works at noon may feel entirely wrong at midnight.

The digital age hasn't made color theory obsolete. It's made it vastly more interesting.`,
    category: "Design",
    author: "Marcus Rivera",
    authorAvatar: "https://i.pravatar.cc/100?img=12",
    date: "February 22, 2026",
    readTime: "5 min read",
    image: "https://picsum.photos/seed/color-theory/1200/800",
    featured: true,
  },
  {
    id: 10,
    slug: "brutalist-web-revival",
    title: "The Brutalist Web Revival: Ugly Is the New Beautiful",
    excerpt:
      "A growing movement of designers is rejecting polish in favor of raw, honest digital experiences.",
    body: `Open most websites today and you'll find the same thing: rounded corners, soft gradients, generous white space, and a sans-serif font that could be Helvetica's friendlier cousin. It's clean. It's professional. And increasingly, it's invisible — so expected that it communicates nothing at all.

Enter the brutalist web revival. Inspired by the concrete-and-function architectural movement of the mid-20th century, brutalist web design strips away decorative elements to expose the raw structure of the medium. Monospaced fonts. Visible grids. Harsh color contrasts. Deliberately "ugly" aesthetics that command attention precisely because they refuse to be pleasant.

The movement has roots in Bloomberg's 2017 website redesign and has gained momentum through sites like Craigslist (unintentionally brutalist) and newer platforms that wear their code on their sleeve.

Critics dismiss it as contrarian — ugliness for ugliness's sake. But proponents argue that brutalist design is honest in a way that conventional web design isn't. Every rounded corner and smooth gradient is a choice to obscure the mechanical nature of the web. Brutalism reveals it.

There's a functional argument too. Brutalist sites tend to be fast — no heavy images, no animation libraries, no JavaScript frameworks. In an era of bloated web pages that take seconds to load, there's something refreshing about a page that appears instantly.

The movement also reflects a broader cultural fatigue with optimization. When everything is A/B tested and conversion-optimized, the result is a web that feels designed by algorithm rather than human. Brutalism asserts human presence — messy, opinionated, and alive.

Beauty is subjective. But honesty never goes out of style.`,
    category: "Culture",
    author: "James Okonkwo",
    authorAvatar: "https://i.pravatar.cc/100?img=3",
    date: "February 18, 2026",
    readTime: "6 min read",
    image: "https://picsum.photos/seed/brutalist-web/1200/800",
    featured: false,
  },
  {
    id: 11,
    slug: "tokyo-underground-fashion",
    title: "Tokyo's Underground Fashion Scene Defies Algorithms",
    excerpt:
      "In Harajuku's back streets, a new wave of designers is creating fashion that can't be replicated by AI.",
    body: `The algorithms can't find them. That's the point.

In the maze of narrow streets behind Harajuku's main drag, a new generation of Tokyo fashion designers is creating work that exists deliberately outside the reach of trend-prediction engines and fast-fashion replicators. Their garments are one-offs, made from salvaged materials, shaped by techniques that resist mass production.

Yuki Tanaka works from a basement studio no larger than a parking space. Her pieces incorporate living moss, hand-forged metal clasps, and fabrics she weaves herself from recycled fishing nets. Each garment takes three to six months to complete. She makes perhaps fifteen pieces a year.

"Speed is the enemy of meaning," she says, carefully attaching a copper clasp she hammered that morning. "If a machine can copy it, it didn't need to exist."

This philosophy connects to a deeper cultural current in Japan — the concept of mono no aware, the bittersweet awareness of impermanence. These designers create beautiful things that are inherently temporary, using materials that age, evolve, and eventually return to the earth.

The community operates largely through word of mouth. Pop-up shows announced hours in advance via encrypted messaging apps. Garments sold only to people who visit in person. No online shopping, no international shipping, no lookbooks.

It's fashion as resistance — against algorithms, against homogenization, against the idea that clothing is content. In a world drowning in product, these designers offer something scarce and precious: clothes that are genuinely, irreducibly human.`,
    category: "Fashion",
    author: "Amara Johnson",
    authorAvatar: "https://i.pravatar.cc/100?img=9",
    date: "February 15, 2026",
    readTime: "5 min read",
    image: "https://picsum.photos/seed/tokyo-fashion/1200/800",
    featured: false,
  },
  {
    id: 12,
    slug: "biophilic-design-revolution",
    title: "Biophilic Design: Bringing Nature Inside Our Buildings",
    excerpt:
      "Research shows that buildings designed with nature in mind dramatically improve human health and productivity.",
    body: `Humans spent 99.9% of their evolutionary history outdoors. We've spent the last century trying to seal ourselves inside climate-controlled boxes. The results, predictably, have not been great for our health.

Biophilic design — the practice of incorporating natural elements into built environments — is architecture's attempt to correct this mismatch. And the evidence for its effectiveness is becoming impossible to ignore.

Studies show that workers in offices with natural light, plants, and views of nature report 15% higher wellbeing and 6% higher productivity than those in conventional offices. Hospital patients in rooms with garden views recover faster and require less pain medication. Students in classrooms with natural ventilation score higher on standardized tests.

The principles go beyond potted plants and big windows. True biophilic design considers natural patterns at every scale: the fractal geometry of a leaf reflected in a building's facade, the dappled light of a forest canopy recreated through perforated screens, the sound of water integrated into a building's HVAC system.

Singapore has emerged as a global leader in biophilic architecture. The city-state's requirement that new developments replace 100% of the green space they displace — on walls, roofs, and elevated gardens — has produced buildings that look like vertical forests.

The economic case is compelling. Green buildings command higher rents, have lower vacancy rates, and save significantly on energy costs. But the human case is even stronger. We are, at our core, creatures of the natural world. Our buildings should remember that.`,
    category: "Architecture",
    author: "Raj Patel",
    authorAvatar: "https://i.pravatar.cc/100?img=8",
    date: "February 12, 2026",
    readTime: "7 min read",
    image: "https://picsum.photos/seed/biophilic/1200/800",
    featured: false,
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}

export function getArticlesByCategory(category: string): Article[] {
  if (category === "All") return articles;
  return articles.filter((a) => a.category === category);
}

export function getRelatedArticles(article: Article, count = 3): Article[] {
  return articles
    .filter((a) => a.id !== article.id && a.category === article.category)
    .slice(0, count);
}
